AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  Domain:
    Type: String
    AllowedValues: [afs, bil, cst, cuc, del, dto, eco, fin, hre, iot, mat, pla, pro, pur, sls]
  DataProduct:
    Type: String
  Environment:
    Type: String
    Description: Specifies the environment of the trigger
    AllowedValues: [test, prod]
  # Job Glue
  Job1:
    Type: String
  Job2:
    Type: String
  Job3:
    Type: String
  Job4:
    Type: String
  Job5:
    Type: String
  Job6:
    Type: String
  Job7:
    Type: String
  Job8:
    Type: String

  ScheduleCron:
    Type: String
    Default: ''
    Description: Cron schedule

Conditions:
  IsScheduled: !Not [ !Equals [ !Ref ScheduleCron, '' ] ]


Resources:
  MatMaterialsWorkflow:
    Type: AWS::Glue::Workflow
    Properties:
      Description: !Sub "dp-${Domain}-${DataProduct} ${Environment} workflow"
      MaxConcurrentRuns: 1
      Name: !Sub "dp-${Domain}-${DataProduct}-glue-workflow-${Environment}"
      Tags:
        Supplier: "Spindox"


  StartTrigger:
    Type: AWS::Glue::Trigger
    Properties:
      Type:
        !If
          - IsScheduled
          - SCHEDULED
          - ON_DEMAND
      Schedule:
        !If
          - IsScheduled
          - !Ref ScheduleCron
          - !Ref 'AWS::NoValue'
      StartOnCreation: true
      Description: "mat-materials Start Trigger"
      Actions:
        - JobName: !Ref Job1
        - JobName: !Ref Job2
        - JobName: !Ref Job3
        - JobName: !Ref Job4
        - JobName: !Ref Job5
        - JobName: !Ref Job6
        - JobName: !Ref Job7
        - JobName: !Ref Job8
      Name: !Sub '${Domain}_${DataProduct}_${Environment}_start_trigger'
      WorkflowName: !Sub "dp-${Domain}-${DataProduct}-glue-workflow-${Environment}"
      Tags:
        Supplier: "Spindox"
