AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  # name
  Domain:
    Type: String
    AllowedValues: [afs, bil, cst, cuc, del, dto, fin, hre, iot, mat, pla, pro, pur, sls]
  SourceSystem:
    Type: String
    AllowedValues: [ago, cpm, hqd, hon, scp, qlk, slf, sap, tms, sno, sie]
  BucketName:
    Type: String
  DataTypeSource:
    Type: String
    Description: Specify the category for the input data of the flow
    AllowedValues: [odm, raw, rel]
  DataTypeTarget:
    Type: String
    Description: Specify the category for the output data of the flow
    AllowedValues: [odm, raw, rel]
  TargetFlow:
    Type: String
  SourceFlow:
    Type: String
    Default: ''
  Description:
    Type: String
  JobRole:
    Type: String
  JobType:
    Type: String
    Default: pythonshell
  ScriptLocation:
    Type: String
    Description: S3 location of the script of the job
  NumberOfWorkers:
    Type: Number
    Description: Specify the number of workers (0 means not set)
    Default: 0
  WorkerType: # not supported for pythonshell
    Type: String
  ExecutionClass:
    Type: String
    AllowedValues: [STANDARD, FLEX]
    Default: STANDARD
  ClusterIdentifier:
    Type: String
  DbUser:
    Type: String
  DbName:
    Type: String
  RedshiftTmpDir:
    Type: String
  DriverJdbc:
    Type: String
  Host:
    Type: String
  Port:
    Type: String
  Region:
    Type: String
  ExtraPyFiles:
    Type: String
  RedshiftConnection:
    Type: String
  IngestionDate:
    Type: String
    Default: YESTERDAY

  # tags
  EnvironmentTag:
    Type: String
    Description: EnvironmentTag
    Default: dev
    AllowedValues: [prd, dev, tst]
  SupplierTag:
    Type: String
    Description: SupplierTag

Resources:
  Job:
    Type: AWS::Glue::Job
    Properties:
      Name: !Sub '${Domain}_${SourceSystem}_from_${BucketName}_${DataTypeSource}_to_${DataTypeTarget}_${TargetFlow}'
      Description: !Ref Description
      Role: !Ref JobRole
      Command:
        Name: glueetl
        PythonVersion: 3
        ScriptLocation: !Ref ScriptLocation
      DefaultArguments:
        --enable-auto-scaling: true
        --BucketName: !Ref BucketName
        --IngestionDate: !Ref IngestionDate
        --SourceFlow: !Ref SourceFlow
        --TargetFlow: !Ref TargetFlow
        --ClusterIdentifier: !Ref ClusterIdentifier
        --DbUser: !Ref DbUser
        --DbName: !Ref DbName
        --RedshiftTmpDir: !Ref RedshiftTmpDir
        --JobRole: !Ref JobRole
        --DriverJdbc: !Ref DriverJdbc
        --Host: !Ref Host
        --Port: !Ref Port
        --Region: !Ref Region
        --extra-py-files: !Ref ExtraPyFiles
      GlueVersion: "4.0"
      NumberOfWorkers: !Ref NumberOfWorkers
      WorkerType: !Ref WorkerType
      ExecutionClass: !Ref ExecutionClass
      Connections:
        Connections:
          - !Ref RedshiftConnection
      NotificationProperty:
        NotifyDelayAfter: 60
      Timeout: 180
      MaxRetries: 0
      Tags:
        Domain: !Ref Domain
        Environment: !Ref EnvironmentTag
        Supplier: !Ref SupplierTag